### ISSUE TITLE
Unexpected changes in PATCH update

### ISSUE THREAD

**Issue by xoac** [async-graphql/async-graphql#1097]
## Expected Behavior

My crate should compile fine with this as dependencies:
```toml
async-graphql = { version = "=4.0.10", features = ["time"]}
```

## Actual Behavior
To make it compile you need to force patch versions on also sub-dependencies

```toml
async-graphql = { version = "=4.0.10", features = ["time"]}
async-graphql-parser = { version = "=4.0.10"}
async-graphql-derive = { version = "=4.0.10"}
```

- - -

Also the version 4.0.10 generate different output than 4.0.14 in case of SDL federation for the same code. I have expected that such change will increase MINOR part of program version.

Possible solutions:
-  revert minor changes in patch and yank the old. Then release federation v2 with 4.1.0
- force `async-graphql` crate to use exactly the same version of dependencies with `=` [composite requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#comparison-requirements)
