### ISSUE TITLE
Union type has Introspection issue

### ISSUE THREAD

**Issue by al8n** [async-graphql/async-graphql#1137]
## Expected Behavior
When using a Union type as query parameter, the introspection call always fail.

Code to reproduce.

**main.rs**
```rust
use async_graphql::{resolver_utils::{enum_value, parse_enum}, extensions::Tracing, EmptyMutation, EmptySubscription};
use async_graphql_axum::{GraphQLRequest, GraphQLResponse};
use axum::{
    extract::{Extension, Path},
    response::{self, IntoResponse},
    routing::post,
    Router, Server,
};

#[derive(Debug, Copy, Clone, PartialEq, Eq, async_graphql::Enum)]
enum Foo {
    A,
    B
}

enum X {
    Single(Foo),
    Multiple(Vec<Foo>),
}

impl async_graphql::InputType for X {
    type RawValueType = Self;

    fn type_name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("X")
    }

    fn create_type_info(registry: &mut async_graphql::registry::Registry) -> String {
        registry.create_input_type::<Self, _>(async_graphql::registry::MetaTypeId::Union, |registry| {
            let mut set = async_graphql::indexmap::IndexSet::new();
            set.insert(<Foo as async_graphql::InputType>::create_type_info(registry));
            set.insert(<Vec<Foo> as async_graphql::InputType>::create_type_info(registry));
            async_graphql::registry::MetaType::Union { 
                name: "X".to_string(), 
                description: None, 
                possible_types: set, 
                visible: None,
                inaccessible: false, 
                tags: &[], 
                rust_typename: std::any::type_name::<Self>()
            }
        })
    }

    fn parse(value: Option<async_graphql::Value>) -> async_graphql::InputValueResult<Self> {
        todo!()
    }

    fn to_value(&self) -> async_graphql::Value {
        todo!()
    }

    fn as_raw_value(&self) -> Option<&Self::RawValueType> {
        todo!()
    }
}

#[derive(Debug, Default)]
struct Query;

#[async_graphql::Object]
impl Query {
    pub async fn x(&self, _x: X) -> async_graphql::Result<u64> {
        todo!()
    }
}

async fn graphql_handler(
    Path(_path): Path<String>,
    schema: Extension<async_graphql::Schema<Query, EmptyMutation, EmptySubscription>>,
    req: GraphQLRequest,
) -> GraphQLResponse {
    schema.execute(req.into_inner()).await.into()
}

#[tokio::main]
async fn main() {
    let schema = async_graphql::Schema::build(Query, EmptyMutation, EmptySubscription)
        .extension(Tracing)
        .validation_mode(async_graphql::ValidationMode::Fast)
        .finish();

    let app = Router::new()
        .route("/", post(graphql_handler))
        .layer(Extension(schema));

    Server::bind(&"127.0.0.1:8000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

**Cargo.toml**
```toml
[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
async-graphql = {version = "4.0.16", features = ["dataloader", "tracing"] }
async-graphql-axum = { version = "4.0.16" }
axum = { version = "0.5", features = ["headers"] }
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1.37"
```

Then run the project and use Postman or any GraphiQL tools, will get Schema Introspection Error. For example, this website: https://cloud.hasura.io/public/graphiql?endpoint=http%3A%2F%2F127.0.0.1%3A8080
will got
<img width="425" alt="image" src="https://user-images.githubusercontent.com/42351146/200597074-d0ba33fb-958d-43ea-9da8-0550cdc069c0.png">
