### ISSUE TITLE
the trait `FromRequest<Body>` is not implemented for `GraphQLRequest` when upgrading to version 5

### ISSUE THREAD

**Issue by robko23** [async-graphql/async-graphql#1286]
## Expected Behavior
It will compile

## Actual Behavior
It throws compile error with message 
```
the trait `FromRequest<Body>` is not implemented for `GraphQLRequest`
```

## Steps to Reproduce the Problem

My minimal code https://gist.github.com/robko23/d04f55168a92dea7bb7d401e89f0e73f

Working `Cargo.toml`:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
tokio = { version = "1.28.0", features = ["full"] }
anyhow = "1.0.71"
async-graphql = "4.0.16"
async-graphql-axum = "4.0.16"
axum = { version = "0.5.17", features =["macros"]}
serde = "1.0.162"
```

Broken `Cargo.toml`:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
tokio = { version = "1.28.0", features = ["full"] }
anyhow = "1.0.71"
async-graphql = "5.0.7"
async-graphql-axum = "5.0.7"
axum = { version = "0.6.18", features =["macros"]}
serde = "1.0.162"
```

## Specifications

- Version: 
`rustc 1.68.0 (2c8cc3432 2023-03-06)`
`cargo 1.68.0 (115f34552 2023-02-26)`
- Platform:
`Linux workstation 6.2.12-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 20 23:38:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
