### ISSUE TITLE
Does async-graphql validate responses?

### ISSUE THREAD

**Issue by RaphaelDarley** [async-graphql/async-graphql#1507]
I was under the impression that async-graphql checked if the response conformed to the schema, and remember seeing errors for it, but now it seems not too.

nb: I've tried switching to version 7, but this doesn't seem to make any difference

```toml
[dependencies]
async-graphql = { version = "6", features = ["dynamic-schema"] }
async-graphql-axum = "6"
axum = "0.6"
tokio = { version = "1.36.0", features = ["full"] }
```

```rust
use async_graphql::http::GraphiQLSource;
use async_graphql::{dynamic::*, Value};
use async_graphql_axum::GraphQL;
use axum::{
    response::{self, IntoResponse},
    routing::get,
    Router, Server,
};

async fn graphiql() -> impl IntoResponse {
    response::Html(GraphiQLSource::build().endpoint("/").finish())
}

#[tokio::main]
async fn main() {
    let query = Object::new("Query").field(Field::new(
        "value",
        TypeRef::named_nn(TypeRef::STRING),
        |_ctx| FieldFuture::new(async move { Ok(Some(Value::from(100))) }),
    ));

    let schema = Schema::build(query.type_name(), None, None)
        .register(query)
        .finish()
        .unwrap();
    let app = Router::new().route("/", get(graphiql).post_service(GraphQL::new(schema)));

    println!("GraphiQL IDE: http://localhost:8001");

    Server::bind(&"127.0.0.1:8001".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```
