### ISSUE TITLE
Cannot find attr `field` when using cfg_attr

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#164]
I am building a library that will optionally enable `async-graphql` support:

```toml
[package]
name = "elastiql"
version = "0.1.0"
authors = ["William Myers <mwilliammyers@gmail.com>"]
edition = "2018"

[features]
default = ["graphql", "builder"]

graphql = ["async-graphql"]
builder = ["typed-builder"]

[dependencies]
async-graphql = { version = "1.14.*", optional = true }
base64 = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
typed-builder = { version = "0.6", optional = true }
```

But when I try to guard the `field` attribute (just like I do with `builder`) like this:

```rust
#[cfg_attr(feature = "graphql", async_graphql::InputObject)]
#[cfg_attr(feature = "builder", derive(typed_builder::TypedBuilder))]
#[derive(Serialize, Clone, Debug)]
pub struct NestedFilterInput {
    path: String,

    query: CompoundFilterInput,

    #[cfg_attr(feature = "graphql", field(default))]
    #[cfg_attr(feature = "builder", builder(default))]
    ignore_unmapped: bool,
}
```

the compiler gives me this error:

```
error: cannot find attribute `field` in this scope
   --> src/search/filter/mod.rs:619:37
    |
619 |     #[cfg_attr(feature = "graphql", field(default))]
    |
```

I have tried:

- ```rust
  #[cfg_attr(feature = "graphql", async_graphql::field(default))]
  ```

- ```rust
  #[cfg(feature = "graphql")]
  use async_graphql::*;
  ```

- adding `async-graphql-derive` to my dependencies

<br>

I think it is because it is not a `derive` based proc-macro...? Are there any ways to accomplish this?
