### ISSUE TITLE
Playground Introspection query returns 404

### ISSUE THREAD

**Issue by edelreal** [async-graphql/async-graphql#366]
## Expected Behavior

A functional playground.

## Actual Behavior

![image](https://user-images.githubusercontent.com/22489176/103371947-b6f91f00-4a9e-11eb-9308-e503615e88bf.png)

I also get an infinite spinner when trying to view the schema:

![image](https://user-images.githubusercontent.com/22489176/103371964-c24c4a80-4a9e-11eb-829a-c256aae64eb6.png)

It looks like the playground is running `IntrospectionQuery`, and it  returns a 404:

![image](https://user-images.githubusercontent.com/22489176/103372099-21aa5a80-4a9f-11eb-9507-0d1f0daab429.png)

## Steps to Reproduce the Problem

1. Create the following `Cargo.toml` file:

   ```toml
   [package]
   name = "example"
   version = "0.1.0"
   authors = ["Elías E. del Real <elias@anewgo.com>"]
   edition = "2018"
   
   [dependencies]
   actix-web = "3"
   async-graphql = "2.4.3"
   async-graphql-actix-web = "2.4.3"
   env_logger = "0.8"
   serde_json = "1.0"
   
   [dev-dependencies]
   actix-rt = "1"
   ```

1. Create an `src` directory, and the following `main.rs` in it:
   
   ```rust
   // Based on https://github.com/actix/examples/blob/master/hello-world/src/main.rs
   use actix_web::{guard, web, App, HttpResponse, HttpServer};
   use async_graphql::{Context, EmptyMutation, EmptySubscription, Object, Schema};
   use async_graphql::http::{playground_source, GraphQLPlaygroundConfig};
   use async_graphql_actix_web::{Request, Response};
   
   struct QueryRoot;
   
   #[Object]
   impl QueryRoot {
     async fn hello(
       &self,
       _ctx: &Context<'_>,
     ) -> &'static str {
       "Hello, world!"
     }
   }
   
   type MySchema = Schema<QueryRoot, EmptyMutation, EmptySubscription>;
   
   async fn index_playground() -> HttpResponse {
     HttpResponse::Ok()
       .content_type("text/html; charset=utf-8")
       .body(playground_source(GraphQLPlaygroundConfig::new("/")))
   }
   
   async fn graphql(schema: web::Data<MySchema>, req: Request) -> Response {
     schema.execute(req.into_inner()).await.into()
   }
   
   #[actix_web::main]
   async fn main() -> std::io::Result<()> {
     let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
       .finish();
   
     println!("🚀 GraphQL server is ready at http://localhost:4001");
   
     HttpServer::new(move || {
       App::new()
         .data(schema.clone())
         .service(web::resource("/graphql").guard(guard::Post()).to(graphql))
         .service(web::resource("/").guard(guard::Get()).to(index_playground))
     })
       .bind("127.0.0.1:4001")?
       .run()
       .await
   }
   ```

1. `cargo run`
1. Browse http://localhost:4001/

## Specifications

On Linux:

- Version: 2.4.3
- Platform: rustc 1.48.0 on Ubuntu 20.04.1 LTS
- Subsystem: None

On Windows:

- Version: 2.4.3
- Platform: rustc 1.46.0 on Ubuntu 20.04.1 LTS on Microsoft Windows 10 Pro
- Subsystem: None
