### ISSUE TITLE
MergedObject with actix-web 4.0.0-beta.3

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#418]
I understand that this is a beta version but it is probably worth pointing out the error so that we can plan ahead.

Even better if you know any work around.

## Description of the feature

Same setup I have from https://github.com/async-graphql/async-graphql/issues/417

Change version to

```
actix-web = "4.0.0-beta.3"
actix-rt = "2.0.2"
```

Got this error

```
  --> actix-web/starwars/src/main.rs:35:65
   |
35 |             .service(web::resource("/").guard(guard::Post()).to(index))
   |                                                                 ^^^^^ the trait `Handler<_, _>` is not implemented for `fn(actix_web::web::Data<async_graphql::Schema<QueryRoot, EmptyMutation, EmptySubscription>>, async_graphql_actix_web::Request) -> impl std::future::Future {index}`
```

**Comment by phungtranminh** [comment]
This might be due to https://github.com/actix/actix-web/pull/1852/files

**Comment by Acidic9** [comment]
Hi is there any update to this? I am also trying to upgrade my Actix app to `0.4.0-beta.3` and am having this issue.

**Comment by Acidic9** [comment]
@phungtranminh for now I've pushed a working fork of async-graphql to my github:
`https://github.com/Acidic9/async-graphql`

You can import with:
```toml
async-graphql = { git = "https://github.com/Acidic9/async-graphql", branch = "actix-beta" }
async-graphql-actix-web = { git = "https://github.com/Acidic9/async-graphql", branch = "actix-beta", package = "async-graphql-actix-web" }
async-graphql-value = { git = "https://github.com/Acidic9/async-graphql", branch = "actix-beta", package = "async-graphql-value" }
```

_Note that you may need to use all async-graphql packages from my repo as it may error because you are using different versions._
