### ISSUE TITLE
bson v2 compatibility

### ISSUE THREAD

**Issue by numToStr** [async-graphql/async-graphql#510]
Yesterday MongoDB released the bson v2-beta crate which gives the following error. I noticed this issue because I was using the re-exported bson module from the MongoDB v2-beta crate.

If you use bson v1 then there will be no issue.

## Error
```
[rustc E0277] [E] the trait bound `mongodb::bson::oid::ObjectId:
async_graphql::OutputType` is not satisfied
required because of the requirements on the impl of `async_graphql::
OutputType` for `&mongodb::bson::oid::ObjectId`

[rustc E0277] [E] the trait bound `mongodb::bson::oid::ObjectId:
async_graphql::Type` is not satisfied
required by `async_graphql::Type::create_type_info`
```

## Code

```rust
use async_graphql::{ComplexObject, SimpleObject};
use bson::oid::ObjectId;
use serde::{Deserialize, Serialize};

#[derive(SimpleObject, Serialize, Deserialize, Debug)]
#[graphql(complex, rename_fields = "snake_case")]
pub struct User {
    #[graphql(name = "_id")]
    _id: ObjectId,
    #[serde(rename = "fullName")]
    full_name: String,
    email: String,
}

#[ComplexObject]
impl User {
    async fn watermark(&self) -> String {
        format!("{} <{}>", self.full_name, self.email)
    }
}
```

Crates:
```toml
async-graphql = { version = "2.8.5", features = ["bson", "dataloader"] } 
bson = "2.0.0-beta"
serde = { version = "1.0.126", features = ["derive"] }
```
