### ISSUE TITLE
actix-web-v4-beta how can i do?

### ISSUE THREAD

**Issue by Oodachi** [async-graphql/async-graphql#553]
![image](https://user-images.githubusercontent.com/34698754/123606492-861c5b80-d82f-11eb-8e48-a48dd13b4f1c.png)

**Comment by sunli829** [comment]
I just updated this branch and now it depends on `actix-web-4.0.0-beta.8`.

**Comment by Oodachi** [comment]
感谢您的回复, 现在我碰到了新的问题.
Thanks for your reply, now I encountered a new problem.

Cargo.toml
```toml
[package]
name = "actix-web-async-graphql-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
async-graphql = { git = "https://github.com/async-graphql/async-graphql.git", branch = "actix-web-v4-beta" }
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql.git", branch = "actix-web-v4-beta" }
```

![image](https://user-images.githubusercontent.com/34698754/123729218-32f5e780-d8c7-11eb-989c-85b111ef2531.png)

现在依然编译不通过, 我发现了一个语法错误在[subscription.rs](https://github.com/async-graphql/async-graphql/blob/actix-web-v4-beta/integrations/actix-web/src/subscription.rs)182行, 于是我fork了一份代码, 修复了这个错误并参考`master`分支将`futues-channel`替换为`async-channel`. 
Now that the compilation fails, I found a syntax error on line 182 of subscription.rs, so I fork a code, and the master fixes this error and refers to the branch to replace futues-channel with async-channel.

现在编译通过了.
Now it compiles.
